[tools]
java = "21"
pnpm = "10.20"
python = "3.13"
fnox = "v1.3.0"
node = "24.11.0"
maven = "3.9.11"
go = "1.25.3"
zig = "0.15.1"
uv = "0.9.7"
gradle = "9.2.0"
kotlin = "2.0"

[settings]
auto_install = true
jobs = 4

